# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/basys3.xdc

# IP: ip/font_rom_ip/font_rom_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==font_rom_ip || ORIG_REF_NAME==font_rom_ip} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/Tudor/Desktop/test_rom/project_1/project_1.gen/sources_1/ip/font_rom_ip/font_rom_ip_ooc.xdc

# XDC: c:/Users/Tudor/Desktop/test_rom/project_1/project_1.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
